IF NOT EXISTS (SELECT * FROM SYS.tables WHERE NAME = 'SecurityMaster' AND SCHEMA_NAME(SCHEMA_ID) = 'dbo')
BEGIN

CREATE TABLE dbo.SecurityMaster
(
	SecurityID INT IDENTITY
	,Ticker VARCHAR(20) NULL
	,Cusip VARCHAR(10) NULL
	,InsertDate DATETIME
	,UpdateDate DATETIME
)

PRINT 'CREATE TABLE dbo.SecurityMaster'

ALTER TABLE dbo.SecurityMaster 
ADD CONSTRAINT PK_SECURITYMASTER PRIMARY KEY (SecurityID)

ALTER TABLE dbo.SecurityMaster
ADD CONSTRAINT DF_SECURITYMASTER_INSERTDATE
DEFAULT GETDATE() FOR InsertDate

ALTER TABLE dbo.SecurityMaster
ADD CONSTRAINT DF_SECURITYMASTER_UPDATEDATE 
DEFAULT GETDATE() FOR UpdateDate

CREATE NONCLUSTERED INDEX IX_SECURITYMASTER_SECURITYID
ON dbo.SecurityMaster (SecurityID)
INCLUDE (Ticker)

END