IF NOT EXISTS (SELECT * FROM SYS.tables WHERE NAME = 'SecurityMaster' AND SCHEMA_NAME(SCHEMA_ID) = 'dbo')
BEGIN

CREATE TABLE dbo.SecurityMaster
(
	SecurityID INT IDENTITY
	,Ticker VARCHAR(20) NULL
	,Cusip VARCHAR(10) NULL
	,LastDevidendDate DATE NULL
	,InsertDate DATETIME NULL
	,UpdateDate DATETIME NULL
)

PRINT 'CREATE TABLE dbo.SecurityMaster'

ALTER TABLE dbo.SecurityMaster 
ADD CONSTRAINT PK_SECURITYMASTER PRIMARY KEY (SecurityID)


CREATE NONCLUSTERED INDEX IX_SECURITYMASTER_SECURITYID
ON dbo.SecurityMaster (SecurityID)
INCLUDE (Ticker)

END